run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      Main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/shagrat164/system-monitoring-daemon
          - github.com/BurntSushi/toml
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/shagrat164/system-monitoring-daemon
          - github.com/stretchr/testify

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
#    - deadcode #is deprecated. Replaced by unused.
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
#    - exportloopref #is deprecated. Replaced by copyloopvar.
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
#    - ifshort #is deprecated.
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
#    - structcheck #is deprecated. Replaced by unused.
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
#    - varcheck #is deprecated. Replaced by unused.
    - wastedassign
    - whitespace
